### ISSUE TITLE
couldn't find "libWPEBackend-default.so" , force closes minibrowser upon launch

### ISSUE THREAD

**Issue by geocine** [Igalia/wpe-android#118]
I was able to reproduce this issue on Windows 10 and on Ubuntu 20.04. I ran this command

```
./tools/scripts/bootstrap.py
```
also tried this
```
./tools/scripts/bootstrap.py --build
```
I was able to successfully compile this on on Android Studio. However when I launch the application on the android TV it justs shows a white screen then shuts down with this error. 

```
2022-08-09 02:05:08.516 12678-12678/com.wpe.tools.minibrowser D/AndroidRuntime: Shutting down VM
2022-08-09 02:05:08.529 12678-12678/com.wpe.tools.minibrowser E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wpe.tools.minibrowser, PID: 12678
    android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class com.wpe.wpeview.WPEView
    Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class com.wpe.wpeview.WPEView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at androidx.fragment.app.Fragment.onCreateView(Fragment.java:2023)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1814)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2976)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2886)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7165)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2938)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.wpe.tools.minibrowser-R0D2fgX6hbOH3jp-nufEVA==/base.apk"],nativeLibraryDirectories=[/data/app/com.wpe.tools.minibrowser-R0D2fgX6hbOH3jp-nufEVA==/lib/arm, /system/lib, /product/lib]]] couldn't find "libWPEBackend-default.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.wpe.wpe.BrowserGlue.<clinit>(BrowserGlue.java:16)
        at com.wpe.wpe.BrowserGlue.setupEnvironment(Native Method)
        at com.wpe.wpe.Browser.initialize(Browser.java:114)
        at com.wpe.wpeview.WPEView.<init>(WPEView.java:55)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at androidx.fragment.app.Fragment.onCreateView(Fragment.java:2023) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1814) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751) 
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2976) 
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2886) 
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263) 
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351) 
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391) 
        at android.app.Activity.performStart(Activity.java:7165) 
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2938) 
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180) 
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6680) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2022-08-09 02:05:08.540 3195-3430/? W/ActivityManager:   Force finishing activity com.wpe.tools.minibrowser/.MainActivity
```

Here is Build log from Android Studio

```
Executing tasks: [:tools:minibrowser:assembleMinApi26Debug] in project 

> Configure project :wpe
Detected ABI: [arm64-v8a]
Use ./tools/scripts/bootstrap.py to install dependencies for more ABIs

> Task :installQATools UP-TO-DATE
> Task :installGitHook UP-TO-DATE
> Task :tools:minibrowser:preBuild UP-TO-DATE
> Task :tools:minibrowser:preMinApi26DebugBuild UP-TO-DATE
> Task :tools:minibrowser:mergeMinApi26DebugNativeDebugMetadata NO-SOURCE
> Task :wpe:preBuild UP-TO-DATE
> Task :wpe:preMinApi26DebugBuild UP-TO-DATE
> Task :wpe:compileMinApi26DebugAidl UP-TO-DATE
> Task :wpe:compileMinApi26DebugRenderscript NO-SOURCE
> Task :wpe:generateMinApi26DebugBuildConfig UP-TO-DATE
> Task :wpe:generateMinApi26DebugResValues UP-TO-DATE
> Task :wpe:generateMinApi26DebugResources UP-TO-DATE
> Task :wpe:packageMinApi26DebugResources UP-TO-DATE
> Task :wpe:parseMinApi26DebugLocalResources UP-TO-DATE
> Task :wpe:processMinApi26DebugManifest UP-TO-DATE
> Task :wpe:generateMinApi26DebugRFile UP-TO-DATE
> Task :wpe:javaPreCompileMinApi26Debug UP-TO-DATE
> Task :wpe:wpeGenServicesMinApi26Debug UP-TO-DATE
> Task :wpe:compileMinApi26DebugJavaWithJavac UP-TO-DATE
> Task :wpe:bundleLibCompileToJarMinApi26Debug UP-TO-DATE
> Task :tools:minibrowser:compileMinApi26DebugAidl NO-SOURCE
> Task :wpe:packageMinApi26DebugRenderscript NO-SOURCE
> Task :tools:minibrowser:compileMinApi26DebugRenderscript NO-SOURCE
> Task :tools:minibrowser:generateMinApi26DebugBuildConfig UP-TO-DATE
> Task :wpe:compileMinApi26DebugLibraryResources UP-TO-DATE
> Task :wpe:writeMinApi26DebugAarMetadata UP-TO-DATE
> Task :tools:minibrowser:checkMinApi26DebugAarMetadata UP-TO-DATE
> Task :tools:minibrowser:generateMinApi26DebugResValues UP-TO-DATE
> Task :tools:minibrowser:generateMinApi26DebugResources UP-TO-DATE
> Task :tools:minibrowser:mergeMinApi26DebugResources UP-TO-DATE
> Task :tools:minibrowser:packageMinApi26DebugResources UP-TO-DATE
> Task :tools:minibrowser:mapMinApi26DebugSourceSetPaths UP-TO-DATE
> Task :tools:minibrowser:parseMinApi26DebugLocalResources UP-TO-DATE
> Task :tools:minibrowser:createMinApi26DebugCompatibleScreenManifests UP-TO-DATE
> Task :wpe:extractDeepLinksMinApi26Debug UP-TO-DATE
> Task :tools:minibrowser:extractDeepLinksMinApi26Debug UP-TO-DATE
> Task :tools:minibrowser:processMinApi26DebugMainManifest UP-TO-DATE
> Task :tools:minibrowser:processMinApi26DebugManifest UP-TO-DATE
> Task :tools:minibrowser:processMinApi26DebugManifestForPackage UP-TO-DATE
> Task :tools:minibrowser:processMinApi26DebugResources UP-TO-DATE
> Task :tools:minibrowser:compileMinApi26DebugKotlin UP-TO-DATE
> Task :tools:minibrowser:javaPreCompileMinApi26Debug UP-TO-DATE
> Task :tools:minibrowser:compileMinApi26DebugJavaWithJavac UP-TO-DATE
> Task :wpe:mergeMinApi26DebugShaders UP-TO-DATE
> Task :wpe:compileMinApi26DebugShaders NO-SOURCE
> Task :wpe:generateMinApi26DebugAssets UP-TO-DATE
> Task :wpe:packageMinApi26DebugAssets UP-TO-DATE
> Task :tools:minibrowser:mergeMinApi26DebugShaders UP-TO-DATE
> Task :tools:minibrowser:compileMinApi26DebugShaders NO-SOURCE
> Task :tools:minibrowser:generateMinApi26DebugAssets UP-TO-DATE
> Task :tools:minibrowser:mergeMinApi26DebugAssets UP-TO-DATE
> Task :tools:minibrowser:compressMinApi26DebugAssets UP-TO-DATE
> Task :tools:minibrowser:checkMinApi26DebugDuplicateClasses UP-TO-DATE
> Task :tools:minibrowser:desugarMinApi26DebugFileDependencies UP-TO-DATE
> Task :tools:minibrowser:mergeExtDexMinApi26Debug UP-TO-DATE
> Task :wpe:bundleLibRuntimeToDirMinApi26Debug UP-TO-DATE
> Task :wpe:processMinApi26DebugJavaRes NO-SOURCE
> Task :wpe:bundleLibResMinApi26Debug NO-SOURCE
> Task :tools:minibrowser:processMinApi26DebugJavaRes NO-SOURCE
> Task :tools:minibrowser:mergeMinApi26DebugJavaResource UP-TO-DATE
> Task :tools:minibrowser:mergeLibDexMinApi26Debug UP-TO-DATE
> Task :tools:minibrowser:dexBuilderMinApi26Debug UP-TO-DATE
> Task :tools:minibrowser:mergeProjectDexMinApi26Debug UP-TO-DATE
> Task :wpe:externalNativeBuildMinApi26Debug
> Task :wpe:mergeMinApi26DebugJniLibFolders UP-TO-DATE
> Task :wpe:mergeMinApi26DebugNativeLibs UP-TO-DATE
> Task :wpe:copyMinApi26DebugJniLibsProjectOnly UP-TO-DATE
> Task :tools:minibrowser:mergeMinApi26DebugJniLibFolders UP-TO-DATE
> Task :tools:minibrowser:mergeMinApi26DebugNativeLibs UP-TO-DATE
> Task :tools:minibrowser:stripMinApi26DebugDebugSymbols UP-TO-DATE
> Task :tools:minibrowser:validateSigningMinApi26Debug UP-TO-DATE
> Task :tools:minibrowser:writeMinApi26DebugAppMetadata UP-TO-DATE
> Task :tools:minibrowser:writeMinApi26DebugSigningConfigVersions UP-TO-DATE
> Task :tools:minibrowser:packageMinApi26Debug UP-TO-DATE
> Task :tools:minibrowser:createMinApi26DebugApkListingFileRedirect UP-TO-DATE
> Task :tools:minibrowser:assembleMinApi26Debug UP-TO-DATE

BUILD SUCCESSFUL in 1s
57 actionable tasks: 1 executed, 56 up-to-date

Build Analyzer results available
```

**Comment by aperezdc** [comment]
The `bootstrap.py` script [makes a symbolic link](https://github.com/Igalia/wpe-android/blob/701faeadc8b65183f7641531de6741d7506cfc85/tools/scripts/bootstrap.py#L350) which makes `libWPEBackend-default.so` point to `libWPEBackend-android.so`. Windows cannot handle symbolic links, so I wonder if that _might_ have something to do, but on the other hand you mention that building on Ubuntu also fails 🤔 

Maybe we should use [wpe_loader_init()](https://webplatformforembedded.github.io/libwpe/loader.html#wpe_loader_init) to configure the name of the backend library and avoid the symlink, or rename the backend library to `libWPEBackend-default.so` instead of using a symlink. In the long run I suppose we will use static linking (see #55) which will make this a non-issue, but it would be nicer to avoid symlinks in the meantime.

**Comment by geocine** [comment]
> The `bootstrap.py` script [makes a symbolic link](https://github.com/Igalia/wpe-android/blob/701faeadc8b65183f7641531de6741d7506cfc85/tools/scripts/bootstrap.py#L350) which makes `libWPEBackend-default.so` point to `libWPEBackend-android.so`. Windows cannot handle symbolic links, so I wonder if that _might_ have something to do, but on the other hand you mention that building on Ubuntu also fails 🤔

I have also tried this on Ubuntu 20.04 but on WSL2 mode , I got the same issue. Is that also the case?

**Comment by geocine** [comment]
I pulled latest `main` to test https://github.com/Igalia/wpe-android/pull/119 , unfortunately I am still getting the same error. 

Before reporting this issue I actually tried manually renaming the file on the `wpe/src/main/cpp/imported/lib/arm64-v8a` from `libWPEBackend-android.so` to `libWPEBackend-default.so` and I got the same error so I kinda of expect this to still not work.  

Are you able to reproduce this on your side or this just happens on my machines?

**Comment by geocine** [comment]
I just noticed this on my `Xiaomi MIBOX4` tv I get this error:
```
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.wpe.tools.minibrowser-_IJg6BFQUg4VI9U5eB_DVA==/base.apk"],nativeLibraryDirectories=[/data/app/com.wpe.tools.minibrowser-_IJg6BFQUg4VI9U5eB_DVA==/lib/arm, /system/lib, /product/lib]]] couldn't find "libWPEBackend-default.so"
```

Notice that it looks for it under `lib/arm` but the one created by `bootstrap.py` is for `lib/arm64-v8a` . I checked the generated APK and the file `libWPEBackend-default.so` is inside the apk but under `lib/arm64-v8a` . 

Do I have to change any configuration , `bootstrap.py` to be able to build for my device?

**Comment by geocine** [comment]
Sorry now the error is gone I have to do `./tools/scripts/bootstrap.py --arch armv7`
