### ISSUE TITLE
WPEView in Fragment crashes after navigating to other Fragment

### ISSUE THREAD

**Issue by zhani** [Igalia/wpe-android#137]
Crash happens when WPEView is used in fragment and navigation from WPEView fragment to some other fragment happens.

Root cause is in RendererASurfaceTransaction. Transaction completed callback is posted to ui thread and meanwhile underlying page has been destroyed because fragment is gone

**Comment by magnumrocha** [comment]
I'm having a similar Issue when close the Activity that holds the WPEView on `v0.1.2` :
```
Cmdline: com.my.package
pid: 7339, tid: 7339, name: abobank.webview  >>> com.my.package <<<
      #00 pc 0000000000070280  /data/app/~~Kj6rwvyiMVvsBUVEAWY9dA==/com.my.package-jgB82WiSedF7nJV80IcEqg==/base.apk!libWPEAndroidRuntime.so (offset 0x1762c000) (RendererSurfaceControl::onTransActionAckOnBrowserThread(std::__ndk1::map<ASurfaceControl*, RendererSurfaceControl::ResourceRef, std::__ndk1::less<ASurfaceControl*>, std::__ndk1::allocator<std::__ndk1::pair<ASurfaceControl* const, RendererSurfaceControl::ResourceRef> > >, SurfaceControl::TransactionStats)+472) (BuildId: 6a19cc591f76b1d409987c99021dcf3bf6677cec)
      #01 pc 0000000000070d10  /data/app/~~Kj6rwvyiMVvsBUVEAWY9dA==/com.my.package-jgB82WiSedF7nJV80IcEqg==/base.apk!libWPEAndroidRuntime.so (offset 0x1762c000) (BuildId: 6a19cc591f76b1d409987c99021dcf3bf6677cec)
      #02 pc 0000000000073528  /data/app/~~Kj6rwvyiMVvsBUVEAWY9dA==/com.my.package-jgB82WiSedF7nJV80IcEqg==/base.apk!libWPEAndroidRuntime.so (offset 0x1762c000) (BuildId: 6a19cc591f76b1d409987c99021dcf3bf6677cec)
      #03 pc 000000000006e5b0  /data/app/~~Kj6rwvyiMVvsBUVEAWY9dA==/com.my.package-jgB82WiSedF7nJV80IcEqg==/base.apk!libWPEAndroidRuntime.so (offset 0x1762c000) (BuildId: 6a19cc591f76b1d409987c99021dcf3bf6677cec)
      #04 pc 00000000000d598c  /data/app/~~Kj6rwvyiMVvsBUVEAWY9dA==/com.my.package-jgB82WiSedF7nJV80IcEqg==/base.apk!libglib-2.0.so (offset 0x1895c000) (g_main_context_dispatch+232)
      #05 pc 000000000006e564  /data/app/~~Kj6rwvyiMVvsBUVEAWY9dA==/com.my.package-jgB82WiSedF7nJV80IcEqg==/base.apk!libWPEAndroidRuntime.so (offset 0x1762c000) (BuildId: 6a19cc591f76b1d409987c99021dcf3bf6677cec)
Binder transaction failure: 394203/29189/-3
Failed to call clean exit callback (Ask Gemini)
android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:586)
	at org.wpewebkit.wpe.IWPEServiceHost$Stub$Proxy.notifyCleanExit(IWPEServiceHost.java:95)
	at org.wpewebkit.wpe.services.WPEService$1.lambda$connect$0$org-wpewebkit-wpe-services-WPEService$1(WPEService.java:63)
	at org.wpewebkit.wpe.services.WPEService$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by zhani** [comment]
I'm able reproduce this in several cases. I found the root cause and I'm preparing a fix
