### ISSUE TITLE
Python script fails when runs: `./tools/scripts/bootstrap.py`

### ISSUE THREAD

**Issue by magnumrocha** [Igalia/wpe-android#172]
```bash
https://wpewebkit.org/android/bootstrap/2.46.0/wpewebkit-android-arm64-2.46.0-runtime.tar.xz [52.47 MiB] 100%  https://wpewebkit.org/android/bootstrap/2.46.0/wpewebkit-android-arm64-2.46.0-runtime.tar.xz - done
Extracting dependencies packages...
Installing dependencies into wpe-android project...
Traceback (most recent call last):
  File "/Users/magnumrocha/Rabobank/wpe-android/./tools/scripts/bootstrap.py", line 529, in <module>
    Bootstrap(args).run()
  File "/Users/magnumrocha/Rabobank/wpe-android/./tools/scripts/bootstrap.py", line 497, in run
    self.install_deps()
  File "/Users/magnumrocha/Rabobank/wpe-android/./tools/scripts/bootstrap.py", line 468, in install_deps
    self._copy_system_libs(wpe_imported_lib_dir)
  File "/Users/magnumrocha/Rabobank/wpe-android/./tools/scripts/bootstrap.py", line 371, in _copy_system_libs
    soname, _ = self._read_elf(lib_path)
  File "/Users/magnumrocha/Rabobank/wpe-android/./tools/scripts/bootstrap.py", line 298, in _read_elf
    p = subprocess.Popen(["readelf", "-d", lib_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'readelf'
```

**Comment by zhani** [comment]
you need to have readelf installed. For example on Ubuntu that's included in binutils package

**Comment by zhani** [comment]
on Mac you can use homebrew to install it `brew install binutils`.
Note that bootstrap script has not been tested on Mac environment

**Comment by magnumrocha** [comment]
I'll test on an Ubuntu machine
