### ISSUE TITLE
minibrowser crashed when startup

### ISSUE THREAD

**Issue by ghoshi168** [Igalia/wpe-android#43]
2021-06-30 16:53:41.359 14489-14489/com.wpe.examples.minibrowser D/AndroidRuntime: Shutting down VM
2021-06-30 16:53:41.360 14489-14489/com.wpe.examples.minibrowser I/QarthLog: [PatchStore] createDisableExceptionQarthFile
2021-06-30 16:53:41.360 14489-14489/com.wpe.examples.minibrowser I/QarthLog: [PatchStore] create disable file for com.wpe.examples.minibrowser uid is 10529
2021-06-30 16:53:41.363 14489-14489/com.wpe.examples.minibrowser E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wpe.examples.minibrowser, PID: 14489
    java.lang.NullPointerException: Attempt to get length of null array
        at android.os.Parcel.createException(Parcel.java:1959)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at com.wpe.wpe.IWPEService$Stub$Proxy.connect(IWPEService.java:111)
        at com.wpe.wpe.services.WPEServiceConnection.onServiceConnected(WPEServiceConnection.java:51)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1932)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1964)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.WrapperInit.main(WrapperInit.java:91)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
2021-06-30 16:53:41.366 14489-14489/com.wpe.examples.minibrowser E/AndroidRuntime: Error reporting crash
    java.lang.RuntimeException: Bad file descriptor
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1149)
        at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:3689)
        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:173)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:1975)
2021-06-30 16:53:41.366 14489-14489/com.wpe.examples.minibrowser I/Process: Sending signal. PID: 14489 SIG: 9

**Comment by ferjm** [comment]
I suspect this is the Web Process restarting after Android killed it. Hopefully #31 will help with this.

**Comment by aperezdc** [comment]
@ghoshi168 Does this still happen? Or can we close this issue?

**Comment by zhani** [comment]
Haven't hit this issue anymore for a long time. Closing this.
